### ISSUE TITLE
Problem with Import functionnality 

### ISSUE THREAD

**Issue by ayadim** [CYS4srl/CYS4-SensitiveDiscoverer#6] opened 2022-11-17 15:00 UTC
Hi,
I hope you are well, so I have an issue importing the saved REGEX list.
first I export the regex list and save it in a CSV extension (sensitiveDiscoverer.csv).
then when I close the burp or even I clear the list and then import my saved list (sensitiveDiscoverer.csv) it is not loaded !!!

regards

**Comment by LorenzoCoppi-cys4** [comment] 2022-11-17 15:03
Duplicate of #1 , it will be fixed in the next release v2.1.0

**Closed by LorenzoCoppi-cys4** 2022-11-17 15:03 UTC
Labels: duplicate

**Comment by ayadim** [comment] 2022-11-17 15:04
ok thank you
